DROP TABLE IF EXISTS user_history CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS moods CASCADE;


CREATE TABLE moods (
  id SERIAL PRIMARY KEY,
  emotion TEXT NOT NULL,
  description TEXT
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE recipes (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  mood_id INTEGER REFERENCES moods(id),
  description TEXT,
  ingredients TEXT[] NOT NULL,
  instructions TEXT
);


CREATE TABLE user_history(
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  mood_id INTEGER REFERENCES moods(id) ON DELETE CASCADE,
 action_type TEXT NOT NULL,
 action_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


